CREATE OR REPLACE FUNCTION "web-market".product_date_autoins()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF
AS $BODY$
BEGIN
    UPDATE PRODUCTS SET INSERT_DATE=NOW() WHERE ID=NEW.ID;
    RETURN NEW;
END; 
$BODY$;

CREATE OR REPLACE FUNCTION "web-market".product_date_update()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF
AS $BODY$
BEGIN
    UPDATE PRODUCTS SET UPDATE_DATE=NOW() WHERE ID=OLD.ID;
    RETURN NULL;
END; 
$BODY$;
